// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyVx6wj6X4TWPvWqqjtslz9WcRFwowG1o',
    appId: '1:435033093012:web:9c4799235a6af6cfc85581',
    messagingSenderId: '435033093012',
    projectId: 'todo-84af8',
    authDomain: 'todo-84af8.firebaseapp.com',
    storageBucket: 'todo-84af8.firebasestorage.app',
    measurementId: 'G-N9Q8GB24X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQSQfBHeJU8dnAAOWrTeIhMPuRzDzkuMo',
    appId: '1:435033093012:android:87cc003372068459c85581',
    messagingSenderId: '435033093012',
    projectId: 'todo-84af8',
    storageBucket: 'todo-84af8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrIciSzyvZ3lAspX1usQ8W3hn94SXqiY',
    appId: '1:435033093012:ios:c71d9046fe08087ac85581',
    messagingSenderId: '435033093012',
    projectId: 'todo-84af8',
    storageBucket: 'todo-84af8.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrIciSzyvZ3lAspX1usQ8W3hn94SXqiY',
    appId: '1:435033093012:ios:c71d9046fe08087ac85581',
    messagingSenderId: '435033093012',
    projectId: 'todo-84af8',
    storageBucket: 'todo-84af8.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyVx6wj6X4TWPvWqqjtslz9WcRFwowG1o',
    appId: '1:435033093012:web:fdb097f8d51df301c85581',
    messagingSenderId: '435033093012',
    projectId: 'todo-84af8',
    authDomain: 'todo-84af8.firebaseapp.com',
    storageBucket: 'todo-84af8.firebasestorage.app',
    measurementId: 'G-TS1MFHPFY6',
  );
}
